export const myJobPostingsRows = [
    {
        id: 1,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 1,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status:'true'

    },
    {
        id: 2,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ANKARA',
        numberOfOpenPositions: 2,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 3,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'İSTANBUL',
        numberOfOpenPositions: 3,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 4,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'OSMANİYE',
        numberOfOpenPositions: 4,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 5,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'KAHRAMANMARAŞ',
        numberOfOpenPositions: 5,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 6,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'GAZİANTEP',
        numberOfOpenPositions: 6,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 7, jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 7,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 8,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'KAYSERİ', numberOfOpenPositions: 8,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 9,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 9,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 10,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 10,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 11,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 11,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 12,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 12,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 13,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 13,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 14,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 14,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 15,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 15,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 16,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 16,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 17,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 17,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 18,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 18,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 19,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 19,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
    {
        id: 20,
        jobPositionTitle: 'Java Developer',
        jobDescription: 'Deneme yazısı deneme deneme deneme',
        cityName: 'ADANA',
        numberOfOpenPositions: 20,
        minimumSalary: '5000',
        maximumSalary: '10000',
        releaseDate: '2021-01-01',
        applicationDeadline: '2022-01-01',
        status: 'true'
    },
];